spring:
  application:
    name: ebankify-1

  datasource:
    url: jdbc:postgresql://localhost:5444/ebankify1
    username: myuser
    password: AZERAZER1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

  security:
    method:
      enabled: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
    com:
      bankapp: INFO

jwt:
  secret: XeFu+{A";U]*CfSdw8)V$E
  expiration: 86400000

server:
  port: 8081
  servlet:
    context-path: /api

  datasource:
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5